import {
  Activity,
  BellRing,
  Check,
  ChevronDown,
  ChevronRight,
  CircleX,
  Clock,
  Copy,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  FileBox,
  FileCheck,
  Focus,
  Footprints,
  Handshake,
  Hexagon,
  Info,
  Keyboard,
  Link,
  ListFilter,
  ListOrdered,
  type LucideIcon,
  OctagonX,
  Pause,
  Pin,
  Play,
  Plus,
  ReceiptText,
  Search,
  Server,
  Settings,
  ShieldCheck,
  Square,
  SunMoon,
  Tag,
  TextSearch,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  Workflow,
  X,
} from "lucide-react";

/**
 * One icon per concept. Components take `LucideIcon` values, so a concept
 * keeps the same glyph everywhere it appears and swapping a glyph is a
 * one-line change here.
 */
export const Icons = {
  host: Server,
  program: Hexagon,
  receipt: ReceiptText,
  stopReport: OctagonX,
  session: Workflow,
  offer: Tag,
  focus: Focus,
  callout: BellRing,
  step: Footprints,
  activity: Activity,
  problem: TriangleAlert,
  error: CircleX,
  warn: TriangleAlert,
  info: Info,
  you: User,
  search: Search,
  add: Plus,
  close: X,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  more: Ellipsis,
  copy: Copy,
  check: Check,
  external: ExternalLink,
  filter: ListFilter,
  pin: Pin,
  pause: Pause,
  play: Play,
  theme: SunMoon,
  settings: Settings,
  stop: Square,
  verify: ShieldCheck,
  blob: FileBox,
  query: TextSearch,
  view: Eye,
  negotiation: Handshake,
  evidence: FileCheck,
  steps: ListOrdered,
  time: Clock,
  keyboard: Keyboard,
  link: Link,
  upload: Upload,
  download: Download,
  remove: Trash2,
} as const satisfies Record<string, LucideIcon>;
