//! Print the browser's TypeScript types for the daemon API.
//! `just client-types` writes the output to `npm/arena0-client/src/types.gen.ts`, and
//! `just check-client` fails when that file is stale.

use arena0_api::{
    ActivityFrame, ApiError, EventFrame, HostRequest, Request, ResponseOk, SyncCursor, SyncFrame,
    Uploaded,
};
use ts_rs::{Config, TS, TypeVisitor};

/// Collects the declaration of every exportable type reachable from the roots.
struct Collector<'a> {
    cfg: &'a Config,
    /// TypeScript name → declaration; BTreeMap gives the sorted output order.
    decls: std::collections::BTreeMap<String, String>,
}

impl TypeVisitor for Collector<'_> {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        if T::output_path().is_none() {
            return;
        }
        let name = T::ident(self.cfg);
        if self.decls.contains_key(&name) {
            return;
        }
        // Insert before descending so recursive JSON shapes terminate.
        self.decls.insert(name, T::decl(self.cfg));
        T::visit_dependencies(self);
        T::visit_generics(self);
    }
}

fn main() {
    // API integer times, positions, counts and lengths stay below 2^53.
    // Identities with a wider range have their own string serialization.
    let cfg = Config::new().with_large_int("number");
    let mut collector = Collector {
        cfg: &cfg,
        decls: std::collections::BTreeMap::new(),
    };
    collector.visit::<Request>();
    collector.visit::<HostRequest>();
    collector.visit::<ResponseOk>();
    collector.visit::<ApiError>();
    collector.visit::<EventFrame>();
    collector.visit::<ActivityFrame>();
    collector.visit::<SyncFrame>();
    collector.visit::<SyncCursor>();
    collector.visit::<Uploaded>();
    collector.visit::<serde_json::Value>();

    println!("// Generated by `just client-types` from crates/arena0-api. Do not edit.\n");
    for declaration in collector.decls.values() {
        // ts-rs leaves a space at the end of a line before each documented
        // field; trimming keeps the generated file clean for `git diff --check`.
        let declaration = declaration
            .lines()
            .map(str::trim_end)
            .collect::<Vec<_>>()
            .join("\n");
        println!("export {declaration}\n");
    }
    println!("export type Response = {{ Ok: ResponseOk }} | {{ Err: ApiError }};");
}
