//! Print the browser's TypeScript bindings for the wire types.
//!
//! `just ui-types` writes the output to `ui/src/sync/protocol.gen.ts`, and
//! `just check-ui` fails when that file is stale.

use arena0_web::{model, protocol};
use ts_rs::{Config, TS};

fn main() {
    // JSON numbers parse as JS numbers; every u64 here is a step, a count, or
    // a millisecond time well below 2^53.
    let cfg = Config::new().with_large_int("number");
    let decls = [
        serde_json::Value::decl(&cfg),
        model::HostRow::decl(&cfg),
        model::ExecutionRow::decl(&cfg),
        model::Lifecycle::decl(&cfg),
        model::PendingRef::decl(&cfg),
        model::EndRow::decl(&cfg),
        model::EndPhase::decl(&cfg),
        model::ActivationRow::decl(&cfg),
        model::ActivationState::decl(&cfg),
        model::ActivationParticipantRow::decl(&cfg),
        model::TerminalRow::decl(&cfg),
        model::TerminalKind::decl(&cfg),
        model::NegotiationMark::decl(&cfg),
        model::NegotiationMarkKind::decl(&cfg),
        model::StepRow::decl(&cfg),
        model::StepEventRow::decl(&cfg),
        model::StepTerminalRow::decl(&cfg),
        model::CalloutRow::decl(&cfg),
        model::ProgramRow::decl(&cfg),
        model::ParticipantRange::decl(&cfg),
        model::ProgramSchemaRow::decl(&cfg),
        model::CalloutSchemaRow::decl(&cfg),
        model::QuerySchemaRow::decl(&cfg),
        model::PhaseRow::decl(&cfg),
        model::ReceiptRow::decl(&cfg),
        model::ReceiptKindRow::decl(&cfg),
        model::ProvenanceRow::decl(&cfg),
        model::OfferRow::decl(&cfg),
        model::ActivityRow::decl(&cfg),
        model::Level::decl(&cfg),
        model::BlobRow::decl(&cfg),
        protocol::ClientFrame::decl(&cfg),
        protocol::ServerFrame::decl(&cfg),
        protocol::Hello::decl(&cfg),
        protocol::DaemonRow::decl(&cfg),
        protocol::StrategyRow::decl(&cfg),
        protocol::RowBatch::decl(&cfg),
        protocol::RowOp::<()>::decl(&cfg),
        protocol::CallResult::decl(&cfg),
        protocol::ErrorRow::decl(&cfg),
        protocol::ErrorCode::decl(&cfg),
        protocol::Op::decl(&cfg),
        protocol::VerifyTarget::decl(&cfg),
        protocol::JoinTarget::decl(&cfg),
        protocol::LaunchArgs::decl(&cfg),
        protocol::Seat::decl(&cfg),
        protocol::SeatDriver::decl(&cfg),
        protocol::ViewReply::decl(&cfg),
        protocol::BlockRow::decl(&cfg),
        protocol::FactRow::decl(&cfg),
        protocol::CellRow::decl(&cfg),
        protocol::RosterEntryRow::decl(&cfg),
        protocol::ToneRow::decl(&cfg),
        protocol::RecordsReply::decl(&cfg),
        protocol::RecordRow::decl(&cfg),
        protocol::RecordEventKind::decl(&cfg),
        protocol::EffectRow::decl(&cfg),
        protocol::EffectKindRow::decl(&cfg),
        protocol::VerifyReply::decl(&cfg),
        protocol::Termination::decl(&cfg),
        protocol::CreatedReply::decl(&cfg),
        protocol::LaunchReply::decl(&cfg),
        protocol::ExecRef::decl(&cfg),
        protocol::ProgramImported::decl(&cfg),
        protocol::BlobImported::decl(&cfg),
    ];
    println!("// Generated by `just ui-types` from crates/arena0-web. Do not edit.\n");
    for decl in decls {
        println!("export {decl}\n");
    }
}
