//! The embedded web UI: a table generated by `build.rs`.

include!(concat!(env!("OUT_DIR"), "/assets.rs"));

/// The bytes and content type of one embedded file; `path` has no leading
/// slash.
pub(crate) fn find(path: &str) -> Option<(&'static [u8], &'static str)> {
    ASSETS
        .iter()
        .find(|(name, _, _)| *name == path)
        .map(|(_, bytes, content_type)| (*bytes, *content_type))
}
