//! Traits for session state, phases, schema introspection, and typed I/O.

use borsh::{BorshDeserialize, BorshSerialize};
use core::convert::Infallible;
use serde::{Deserialize, Serialize};

use crate::{CalloutSchema, Primitive, PrimitiveRouteSchema, QuerySchema};

/// Static declaration of a lifecycle phase.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PhaseDecl {
    pub name: &'static str,
    pub description: &'static str,
    pub is_default: bool,
    pub is_terminal: bool,
}

/// Static declaration of a local pending label.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PendingDecl {
    pub name: &'static str,
}

/// A program's lifecycle phase enum. Generated by `#[arena0::phases]`.
pub trait Arena0Phase: Copy + 'static {
    /// Static phase declarations for metadata export.
    const DECLS: &'static [PhaseDecl];

    /// The human-readable name of this phase variant.
    fn as_str(self) -> &'static str;

    /// Whether this phase is terminal.
    fn is_terminal(self) -> bool;

    /// Whether this phase is the starting default.
    fn is_default(self) -> bool {
        false
    }
}

impl Arena0Phase for Infallible {
    const DECLS: &'static [PhaseDecl] = &[];

    fn as_str(self) -> &'static str {
        match self {}
    }

    fn is_terminal(self) -> bool {
        match self {}
    }
}

/// A program's local pending labels. Generated by `#[arena0::pending]`.
pub trait Arena0Pending: Copy + 'static {
    /// Static pending labels for metadata and diagnostics.
    const DECLS: &'static [PendingDecl];

    /// The trace label for this pending variant.
    fn as_str(self) -> &'static str;
}

/// Introspection allowlist for values that appear in program metadata.
///
/// Implementations are allowlisted by the SDK. This prevents unsupported Rust
/// types from entering program metadata only because their upstream crates
/// happen to implement the schema trait. Serialization behavior is declared
/// separately at each boundary; this trait never defines it.
pub trait ProgramValue: schemars::JsonSchema + 'static {
    /// The public JSON Schema document for this value's shape.
    #[must_use]
    fn json_schema() -> crate::JsonSchemaDocument
    where
        Self: Sized,
    {
        crate::JsonSchemaDocument::for_type::<Self>()
    }
}

/// Shared-visible replicated state.
///
/// Shared state is serialized, hashed, traced, and compared across
/// participants. Local state is intentionally not part of this trait.
pub trait SharedState:
    Default + serde::Serialize + BorshSerialize + BorshDeserialize + ProgramValue + Primitive + 'static
{
    /// Upper bound on borsh-serialized shared state size in bytes.
    const STATE_MAX: usize;

    /// Primitive routing metadata generated from `#[primitive]` fields.
    #[doc(hidden)]
    fn __primitive_routes() -> Vec<PrimitiveRouteSchema> {
        Vec::new()
    }

    /// Capabilities required by primitive fields in this shared state.
    #[doc(hidden)]
    fn __required_capabilities() -> Vec<arena0_program::Capability> {
        Vec::new()
    }
}

/// Local, participant-private state.
///
/// Local state is semantic state even though it is not part of shared hashes.
/// The guest serializes it with the type's stock Borsh implementation at every
/// fresh-call boundary. Hidden Wasm memory and globals are not local state.
pub trait LocalState: Default + BorshSerialize + BorshDeserialize + 'static {}

impl<T> LocalState for T where T: Default + BorshSerialize + BorshDeserialize + 'static {}

/// Opt-in redacted debug projection for participant-local state.
///
/// Implemented by `#[arena0::local]` for local structs that want traces,
/// snapshots, and viewers to include participant-private debug state. The
/// returned value must already redact secret fields.
pub trait LocalDebug {
    /// Return a redacted JSON snapshot of the local state.
    fn local_debug_snapshot(&self) -> serde_json::Value;
}

/// Runtime-managed lifecycle phase field.
///
/// `#[arena0::state]` rewrites the shared phase field to this wrapper so
/// ordinary author code cannot assign a bare `Phase` through shared state
/// mutation.
/// Handlers move phases by returning [`Transition::To`](crate::Transition::To);
/// the runtime applies that transition through [`PhasedSharedState::__set_phase`].
///
/// ```compile_fail
/// use arena0::{phases, state};
///
/// #[arena0::phases]
/// enum Phase {
///     #[phase(default)]
///     Setup,
///     Done,
/// }
///
/// #[arena0::state(max = 64)]
/// pub struct State {
///     phase: Phase,
/// }
///
/// let mut state = State::default();
/// state.phase = Phase::Done;
/// ```
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Hash,
    BorshSerialize,
    BorshDeserialize,
    Serialize,
    Deserialize,
    schemars::JsonSchema,
)]
#[serde(transparent)]
pub struct ManagedPhase<P: Arena0Phase>(P);

impl<P: Arena0Phase + ProgramValue> ProgramValue for ManagedPhase<P> {}

impl<P: Arena0Phase + Default> Default for ManagedPhase<P> {
    fn default() -> Self {
        Self(P::default())
    }
}

impl<P: Arena0Phase> ManagedPhase<P> {
    /// Return the current phase value.
    #[must_use]
    pub fn get(self) -> P {
        self.0
    }

    #[doc(hidden)]
    #[must_use]
    pub fn __new(phase: P) -> Self {
        Self(phase)
    }
}

impl<P: Arena0Phase> From<ManagedPhase<P>> for String {
    fn from(phase: ManagedPhase<P>) -> Self {
        phase.get().as_str().to_string()
    }
}

/// Shared state with a managed lifecycle phase.
///
/// Generated by `#[arena0::state]` for phased shared structs. Contains the
/// phase accessor and serialization size bound.
pub trait PhasedSharedState: SharedState {
    /// The phase enum type for this program.
    type Phase: Arena0Phase;

    /// The current lifecycle phase.
    fn phase(&self) -> Self::Phase;

    /// Runtime-only phase mutation used to apply a returned [`Transition`](crate::Transition).
    #[doc(hidden)]
    fn __set_phase(&mut self, phase: Self::Phase);
}

/// Trait for typed callout declarations. Generated by `#[arena0::callouts]`.
pub trait Arena0Callout: 'static {
    /// The corresponding request enum for prompting callouts.
    type Request: Arena0TypedCalloutRequest<Output = Self::Response>;

    /// The response enum delivered to `on_input`.
    type Response: serde::de::DeserializeOwned + ProgramValue + 'static;

    /// Public schemas for each callout variant, in callout discriminant order.
    fn schemas() -> Vec<CalloutSchema>;

    /// Construct the typed response from host bytes (callout index + JSON data).
    ///
    /// The host forwards the agent's JSON answer unchanged. This method parses
    /// it into the correct response variant with the DTO's stock Serde
    /// implementation.
    fn from_raw(callout_index: u32, data: Vec<u8>) -> Self::Response;

    /// Convert a response into its host wire form: `(callout_index, data)`.
    ///
    /// Inverse of [`from_raw`](Arena0Callout::from_raw). Used by
    /// a host-side harness to construct `Event::InputReceived` for Wasm
    /// dispatch.
    fn to_event_data(response: &Self::Response) -> (u32, Vec<u8>);
}

/// Trait for individual callout request variants. Generated by `#[arena0::callout]`.
pub trait Arena0CalloutRequest: serde::Serialize {
    /// The discriminant index identifying this request variant.
    fn callout_index(&self) -> u32;

    /// Expected output type name for typed callout diagnostics.
    fn expected_type_name(&self) -> Option<&'static str> {
        None
    }
}

/// Request-level output contract for generated callout structs.
///
/// Unlike [`CalloutSpec`], this trait does not need the enclosing
/// [`Program`](crate::Program).
/// It lets effect builders preserve the exact awaited output type directly
/// from a concrete request such as `callouts::ChooseMove`.
pub trait Arena0TypedCalloutRequest: Arena0CalloutRequest {
    /// Output returned when this concrete callout resolves.
    type Output: serde::de::DeserializeOwned + ProgramValue + 'static;
}

/// Per-callout type contract generated for typed callout authoring.
///
/// The umbrella [`Arena0Callout`] implementation remains the runtime format. This
/// trait maps one concrete callout request, such as `callouts::ChooseMove`, to its
/// exact output type so higher-level shells and harnesses do not have to unwrap
/// the broad program input enum by hand.
pub trait CalloutSpec<P: crate::Program>: Arena0CalloutRequest + Sized {
    /// Discriminant index for this concrete callout request.
    const CALLOUT_INDEX: u32;

    /// Variant name used in diagnostics.
    const CALLOUT_NAME: &'static str;

    /// Output returned when this specific callout resolves.
    type Output: serde::de::DeserializeOwned + ProgramValue + 'static;

    /// Convert the concrete callout into the program's umbrella callout enum.
    fn into_callout(self) -> P::Callout;

    /// Convert a typed output into the program's umbrella input enum.
    fn into_input(output: Self::Output) -> P::Input;

    /// Decode the program input enum into this callout's exact output type.
    fn decode(input: P::Input) -> Result<Self::Output, crate::InputFault>;
}

/// Trait for typed read-only queries. Generated by `#[arena0::query]`.
pub trait Arena0Query: serde::de::DeserializeOwned + ProgramValue {
    /// The response type returned by `ProgramQuery::query`.
    type Response: serde::Serialize + ProgramValue;

    /// Public schemas for each query endpoint.
    fn schemas() -> Vec<QuerySchema> {
        Vec::new()
    }
}

impl Arena0Query for () {
    type Response = ();
}

impl Arena0Callout for () {
    type Request = ();
    type Response = ();

    fn schemas() -> Vec<CalloutSchema> {
        vec![]
    }

    fn from_raw(_callout_index: u32, _data: Vec<u8>) -> Self::Response {
        panic!("program does not accept callouts")
    }

    fn to_event_data(_response: &Self::Response) -> (u32, Vec<u8>) {
        panic!("program does not accept callouts")
    }
}

impl Arena0CalloutRequest for () {
    fn callout_index(&self) -> u32 {
        0
    }
}

impl Arena0TypedCalloutRequest for () {
    type Output = ();
}
