[package]
name = "arena0-minimal-program"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
arena0-sdk = "=0.1.0"
borsh = { version = "1.6", features = ["derive"] }
serde = { version = "1", features = ["derive"] }

[workspace]
